name: Deploy to Github Pages

on:
  push:
    branches: [ "master" ]
  # pull_request:
  #   branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

# Sets the GITHUB_TOKEN permissions to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install wasm-pack
      run: npm install -g wasm-pack 
    - name: Run tests
      working-directory: ./league-sim-backend
      run: cargo test --verbose
    - name: Build WASM
      working-directory: ./league-sim-backend
      run: wasm-pack build
    - name: Use Node.js 22.x
      uses: actions/setup-node@v4
      with:
        node-version: 22.x
        cache: 'npm'
        cache-dependency-path: ./league-sim-frontend/package-lock.json
    - run: npm ci
      working-directory: ./league-sim-frontend
    - run: npm install
      working-directory: ./league-sim-frontend
    - run: npm run build
      working-directory: ./league-sim-frontend
    - name: Setup Pages
      uses: actions/configure-pages@v4
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        # Upload dist folder
        path: './league-sim-frontend/dist'
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
